# ----------------------------------------------------------------------------------------------------
# Template to deploy a SQL Dacpac File to a SQL Database
# ----------------------------------------------------------------------------------------------------
parameters: 
- name: environmentName
  default:  'DEV'
- name: appFolderName
  default: ''
- name: appSolutionName
  default: ''
- name: appProjectName
  default: ''
- name: artifactName
  default: 'dacpac'

# ------------------------------------------------------------------------------------------------------------------------
jobs:
- deployment: Build${{ parameters.environmentName }}Schema
  displayName: Initialize ${{ parameters.environmentName }} Build Schema
  environment: ${{ parameters.environmentName }}

- job: BuildDB${{ parameters.environmentName }}Schema
  displayName: Build ${{ parameters.environmentName }} Schema
  variables:
    - name: environmentNameUpper
      value: ${{ upper(parameters.environmentName) }}
    - name: environmentNameLower
      value: ${{ lower(parameters.environmentName) }}
    - name: buildPlatform
      value: 'Any CPU'
    - name: buildConfiguration
      value: 'Release'

  steps:
  - task: CmdLine@2
    inputs:
      script: |
        echo "serviceConnectionName=$(serviceConnectionName)"
        echo "environmentNameUpper=$(environmentNameUpper)"
        echo "environmentNameLower=$(environmentNameLower)"
        echo "appFolderName=${{ parameters.appFolderName }}"
        echo "appSolutionName=${{ parameters.appSolutionName }}"
        echo "appProjectName=${{ parameters.appProjectName }}"
        echo "artifactName=${{ parameters.artifactName }}"
        echo "Directory of pipeline workspace:"
        tree $(Pipeline.Workspace)
    displayName: 'Display Variables and Tree'
    continueOnError: true

  - task: VSBuild@1
    displayName: Build DacPac
    inputs:
      solution: '${{ parameters.appFolderName }}/${{ parameters.appSolutionName }}.sln'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
      msbuildArgs: /p:DropObjectsNotInSource=False

      # In theory, these parms drop all EXCEPT for these things....: (haven't tested them...)
      #    msbuildArgs: /p:DropObjectsNotInSource=True /p:ExcludeObjectTypes=Users;Logins;RoleMembership;Permissions;Credentials;DatabaseScopedCredentials
      # For more info, see:
      # https://learn.microsoft.com/en-us/archive/blogs/ssdt/new-advanced-publish-options-to-specify-object-types-to-exclude-or-not-drop      
      # https://learn.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage?view=sql-server-ver16
      # https://stackoverflow.com/questions/17402904/prevent-dropping-of-users-when-publishing-a-dacpac-using-sqlpackage-exe

  - task: PublishBuildArtifacts@1
    displayName: Save DacPac Artifact
    inputs:
      PathtoPublish: '$(Pipeline.Workspace)\s\${{ parameters.appFolderName }}\${{ parameters.appProjectName }}\bin\Release\${{ parameters.appProjectName }}.dacpac'
      ArtifactName: '${{ parameters.artifactName }}'
      publishLocation: 'Container'
