# ------------------------------------------------------------------------------------------------------------------------
# Pipeline Template to deploy Azure Resources Only
# ------------------------------------------------------------------------------------------------------------------------
parameters:
- name: environments
  type: object
  default: ['DEV']
- name: singleEnvironment
  default: 'false'
- name: runGHASScan
  default: 'false'
- name: runMSDevSecOpsScan
  default: 'false'
- name: appFolderName
  default: ''
- name: appSolutionName
  default: ''
- name: appProjectFolderName
  default: ''
- name: appProjectName
  default: ''
- name: appProjectExtension
  default: 'csproj' # or 'sqlproj' (!)

# ----------------------------------------------------------------------------------------------------
stages:
- ${{ if or(eq(lower(parameters.runMSDevSecOpsScan), 'true'), eq(lower(parameters.runGHASScan), 'true')) }}:
  - stage: ScanApplication
    displayName: Scan Application
    jobs:
    - template: templates/scan-code-template.yml
      parameters:
        environmentName: 'DEV'
        runMSDevSecOpsScan: ${{ parameters.runMSDevSecOpsScan }}
        runGHASScan: ${{ parameters.runGHASScan }}
        appFolderName: ${{ parameters.appFolderName }}
        appSolutionName: ${{ parameters.appSolutionName }}
        appProjectFolderName: ${{ parameters.appProjectFolderName }}
        appProjectExtension: ${{ parameters.appProjectExtension }}

- ${{ each environmentName in parameters.environments }} :
  - stage: CreateInfra${{ environmentName }}
    displayName: Create ${{ environmentName }} Resources
    # Condition is build complete and a single environment is being deployed, 
    # or the environment is 'dev', or if qa/prod, the previous stage (dev->qa or qa->prod) succeeded
    condition: or(eq(${{ parameters.singleEnvironment }}, 'true'), and(eq(upper('${{ environmentName }}'), 'QA'), succeeded('CreateInfraDEV')), and(eq(upper('${{ environmentName }}'), 'PROD'), succeeded('CreateInfraQA')))
    jobs:
    - template: templates/create-infra-template.yml
      parameters:
        environmentName: ${{ environmentName }}
