# ------------------------------------------------------------------------------------------------------------------------
# Pipeline Template to build and deploy Azure Resources and Database
# ------------------------------------------------------------------------------------------------------------------------
parameters:
- name: environments
  type: object
  default: ['DEMO']
- name: appFolderName
  default: ''
- name: appSolutionName
  default: ''
- name: appProjectFolderName
  default: ''
- name: appProjectName
  default: ''
- name: appProjectExtension
  default: 'csproj' # or 'sqlproj' (!)
- name: runGHASScan
  default: 'false'
- name: runMSDevSecOpsScan
  default: 'false'

# ----------------------------------------------------------------------------------------------------
stages:
- ${{ if or(eq(lower(parameters.runMSDevSecOpsScan), 'true'), eq(lower(parameters.runGHASScan), 'true')) }}:
  - stage: ScanApplication
    displayName: Scan Application
    jobs:
    - template: templates/scan-code-template.yml
      parameters:
        environmentName: 'DEMO'
        runMSDevSecOpsScan: ${{ parameters.runMSDevSecOpsScan }}
        runGHASScan: ${{ parameters.runGHASScan }}
        appFolderName: ${{ parameters.appFolderName }}
        appSolutionName: ${{ parameters.appSolutionName }}
        appProjectFolderName: ${{ parameters.appProjectFolderName }}
        appProjectExtension: ${{ parameters.appProjectExtension }}

- stage: BuildDacPac
  displayName: Build DACPAC
  jobs:
  - template: templates/dacpac-build-template.yml
    parameters:
      environmentName: 'DEMO'
      appFolderName: ${{ parameters.appFolderName }}
      appSolutionName: ${{ parameters.appSolutionName }}
      appProjectName: ${{ parameters.appProjectName }}
      artifactName: 'dacpac'

# ----------------------------------------------------------------------------------------------------
- ${{ each environmentName in parameters.environments }} :
  - stage: CreateInfra${{ environmentName }}
    displayName: Create ${{ environmentName }} Resources
    dependsOn: BuildDacPac
    condition: succeeded('BuildDacPac')
    jobs:
    - template: templates/create-infra-template.yml
      parameters:
        environmentName: ${{ environmentName }}

  - stage: Deploy${{ environmentName }}Schema
    displayName: Deploy ${{ environmentName }} Schema
    dependsOn: CreateInfra${{ environmentName }}
    condition: succeeded('CreateInfra${{ environmentName }}')
    jobs:
    - template: templates/dacpac-deploy-template.yml
      parameters:
        environmentName: ${{ environmentName }}
        artifactName: 'dacpac'
        appProjectName: ${{ parameters.appProjectName }}
