--------------------------------------------------------------------------------------
-- This file contains SQL statements that will be appended to the build script.
--------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------
-- Create default joke data
------------------------------------------------------------------------------------------------------------------------

Declare @RemovePreviousJokes varchar(1) = 'N' --   --> don't delete the existing data!

Declare @tmpCategory Table (
  JokeCategoryTxt nvarchar(500)
)
Declare @tmpJokes Table (
  JokeId int identity(1,1),
  JokeTxt nvarchar(max),
  JokeCategoryTxt nvarchar(500),
  Attribution nvarchar(500),
  ImageTxt nvarchar(max)
)

------------------------------------------------------------------------------------------------------------------------
Delete From @tmpCategory
INSERT INTO @tmpCategory (JokeCategoryTxt) VALUES
  ('Aging'),
  ('Bad Puns'),
  ('Camping'),
  ('Chickens'),
  ('Christmas'),
  ('Dad'),
  ('Did''ya Hear'),
  ('Engineers'),
  ('Good Question!'),
  ('Halloween'),
  ('Hipsters'),
  ('Jobs'),
  ('Knock Knock'),
  ('Pirates'),
  ('Programmers'),

  ('Science'),

  ('What do you call...')

Delete From @tmpJokes
INSERT INTO @tmpJokes (JokeCategoryTxt, JokeTxt, Attribution, ImageTxt) VALUES
  ('Aging', '60 might be the new 40, but 9:00 pm is the new midnight.', NULL, 'A clock late at night'),
  ('Aging', 'I remember being able to get up without making sound effects.', NULL, 'An old person getting up out of a chair'),
  ('Aging', 'I run like the winded.', NULL, 'A runner that is bent over and breathing really hard'),
  ('Aging', 'The older I get, the earlier it gets late.', NULL, 'A clock late at night'),
  ('Bad Puns', 'A bicycle can''t stand on its own because it''s two-tired.', NULL, 'A bicycle that fell over'),
  ('Bad Puns', 'A boiled egg is hard to beat.', NULL, 'A boiled egg'),
  ('Bad Puns', 'A chicken crossing the road is poultry in motion.', NULL, 'A chicken crossing the road'),
  ('Bad Puns', 'A friend of mine tried to annoy me with bird puns, but I soon realized that toucan play at that game.', NULL, 'An annoyed toucan'),
  ('Bad Puns', 'A pun entered the room and kills 10 people. Pun in, ten dead.', NULL, 'A pun with a gun'),
  ('Bad Puns', 'Broken pencils are pointless.', NULL, 'A broken pencil'),
  ('Bad Puns', 'Did you know they won''t be making yard sticks any longer?', NULL, 'A yard stick'),
  ('Bad Puns', 'Entropy: it ain''t what it used to be.', NULL, 'Entropy'),
  ('Bad Puns', 'He often broke into song because he couldn''t find the right key.', NULL, 'Someone singing off key'),
  ('Bad Puns', 'I broke my finger last week. On the other hand, I''m okay.', NULL, 'A person with a broken finger'),
  ('Bad Puns', 'I didn''t like my new beard, but then it grew on me.', NULL, 'A man with a short beard'),
  ('Bad Puns', 'I heard about a lab in California growing medical marijuana - a flock of terns landed in their field and ate all their weed. They say no tern was left unstoned.', NULL, 'A flock of terns landing in a field'),
  ('Bad Puns', 'I heard Swedish war ships have bar codes on the sides. That way, when they return to port, they can Scandinavian', NULL, 'A Swedish Navy ship with a bar code on the side'),
  ('Bad Puns', 'I just swallowed some food coloring. I feel like I''ve dyed a little inside.', NULL, 'A bottle of food coloring'),
  ('Bad Puns', 'I know a guy who''s addicted to brake fluid. Says he can stop anytime.', NULL, 'A guy with a can of brake fluid'),
  ('Bad Puns', 'I once entered 10 puns in a best pun contest and thought I would win, but no pun in ten did', NULL, 'A participation trophy'),
  ('Bad Puns', 'I pulled a muscle digging for gold. It was a miner injury.', NULL, 'A miner digging for gold'),
  ('Bad Puns', 'I tried to catch some fog, but I mist', NULL, 'A very foggy day'),
  ('Bad Puns', 'I wanted to watch the world origami championships, but it was only on paper view.', NULL, 'Origami contest'),
  ('Bad Puns', 'I was going to buy a money belt for our latest trip, but it seemed like such a waist of money', NULL, 'A man with a money belt'),
  ('Bad Puns', 'I, for one, like Roman Numerals.', NULL, 'Roman Numerals'),
  ('Bad Puns', 'In the army of corny jokes, I''m the kernel', NULL, 'A man standing by a field of corn'),
  ('Bad Puns', 'It''s hard to explain puns to kleptomaniacs because they always take things literally.', NULL, 'A burglar stealing from a store'),
  ('Bad Puns', 'I''ve always admired fishermen - they are reel men.', NULL, 'A fisherman with a rod and reel'),
  ('Bad Puns', 'Soup that tastes great is souper', NULL, 'A bowl of great tasting soup'),
  ('Bad Puns', 'Steak Puns: now there''s a medium where anything well done is rare.', NULL, 'A well done steak'),
  ('Bad Puns', 'The Energizer Bunny was arrested - charged with battery.', NULL, 'The Energizer Bunny'),
  ('Bad Puns', 'The fastest way to quit being vegan is cold turkey.', NULL, 'A very cold turkey'),
  ('Bad Puns', 'The inventor of auto-correct just died -- may he roast in piss.', NULL, 'An auto-correct failure'),
  ('Bad Puns', 'The short fortune teller who escaped from prison was a small medium at large.', NULL, 'A fortune teller who escaped from prison'),
  ('Bad Puns', 'Time flies like an arrow. Fruit flies like a banana.', NULL, 'A banana being shot by an arrow'),
  ('Bad Puns', 'To whoever took my Microsoft Office: I will find you. You have my Word.', NULL, 'Microsoft Office being stolen'),
  ('Bad Puns', 'Two Eskimos sitting in a kayak were chilly, so they lit a fire in the craft. Unsurprisingly it sank, proving once again that you can''t have your kayak and heat it too.', NULL, 'Two cold Eskimos sitting in a kayak'),
  ('Bad Puns', 'Whiteboards are remarkable.', NULL, 'A Whiteboards full of hand drawn images'),
  ('Bad Puns', 'You know how farmers make crop circles? They use a protractor', NULL, 'A crop circle and a tractor'),
  ('Camping', 'An RV is the best investment you can make in wheel estate!', NULL, 'A fifth wheel RV'),
  ('Camping', 'God gave us shin bones so we could find trailer hitches in the dark.', NULL, 'Hitting your shin on something'),
  ('Camping', 'How many RVers does it take to change a light bulb? Only one - the others are dealing with their grey water issues.', NULL, 'A person dumping the black tank on an RV'),
  ('Camping', 'Yo momma''s so fat the bears have to hide their food from her when she goes camping.', NULL, 'Bears looking for food in a campsite'),
  ('Camping', 'You can''t run through a campsite. You can only ran. Because it''s past tents.', NULL, 'A person running past a tent'),
  ('Camping', 'You might be a RVer if roughing it is only water and electric.', NULL, 'Glamping in an RV'),
  ('Camping', 'You might be a RVer if you find yourself spending an inordinate amount of time discussing the merits of different toilet papers.', NULL, 'A person on a toilet'),
  ('Camping', 'You might be a RVer if you hang a ladder on your ladder.', NULL, 'A ladder on the back of an RV'),
  ('Camping', 'You might be a RVer if you think 300 square feet of living space is really living!', NULL, 'A small RV'),
  ('Camping', 'You might be a RVer if you think it is completely normal to drive a F-450(or any dually) to the store to pick up a few groceries.', NULL, 'A Ford F-450 dually truck'),
  ('Camping', 'You might be a RVer if you think the capital of the United States is Elkhart, Indiana', NULL, 'Map of Elkhart, Indiana'),
  ('Chickens', 'Did''ya hear about the chicken who could only lay eggs in the winter? She was no spring chicken.', NULL, 'A chicken laying eggs in the winter'),
  ('Chickens', 'I have a dream that one day chickens will be able to cross the road without being judged on their motives.', NULL, 'A chicken crossing the road and a judge'),
  ('Chickens', 'What do you call a chicken crossing the road? Poultry in motion.', NULL, 'A chicken running across the road'),
  ('Chickens', 'What do you get when a chicken lays an egg on top of a barn? An eggroll.', NULL, 'A chicken on the roof of a barn'),
  ('Chickens', 'Which day of the week do chickens hate most? Fry-day!', NULL, 'Fried chicken'),
  ('Chickens', 'Why did the chicken cross the basketball court? He heard the referee calling fowls', NULL, 'A basketball referee dressed like a chicken'),
  ('Chickens', 'Why did the chicken cross the playground? To get to the other slide.', NULL, 'A chicken on a childrens playground'),
  ('Christmas', 'Did you know Santa has a 10th reindeer Olive? It''s in the Rudolph song - ''Olive the other reindeer''', NULL, 'A reindeer with a green nose'),
  ('Christmas', 'KK/WT: Ho-Ho ? (Ho-Ho-Who?) Your Santa impression needs some work', NULL, 'Santa saying ho-ho-ho'),
  ('Christmas', 'What do you call people who are afraid of Santa? Claustrophobic', NULL, 'Santa in a room that is way too small for him'),
  ('Christmas', 'What do you call Santa''s helpers? Subordinate Clauses', NULL, 'Santa''s elves'),
  ('Christmas', 'What kind of cars do Santa''s elves drive? Toy-otas', NULL, 'Santa driving a Toyota'),
  ('Dad', 'Breaking news: A red ship and a blue ship have collided in the Caribbean... apparently, the survivors are marooned.', NULL, 'Two ships crashing in the ocean'),
  ('Dad', 'Cannibal says: a sandwich is a sandwich, but a manwich is a meal!', NULL, 'A sloppy joe sandwich'),
  ('Dad', 'I entered a dad joke competition and won $1000. It was a grand dad joke.', NULL, 'A man winning the grand prize'),
  ('Dad', 'I really feel like I have a bad posture. I have a hunch.', NULL, 'A person hunched over '),
  ('Dad', 'If a clown farts, does it smell funny?', NULL, 'A clown farting'),
  ('Dad', 'I''m going to a Fibonacci conference this year. They promise it will be as big as the last two put together!', NULL, 'A very large Fibonacci sequence'),
  ('Dad', 'I''m pretty sure that hotel receptionist was checking me out', NULL, 'A hotel receptionist looking at you'),
  ('Dad', 'It''s inappropriate to make a dad joke if you''re not a dad. That''s a faux pa.', NULL, 'Someone pretending to be a dad'),
  ('Dad', 'Joseph Stalin should have known communism wouldn''t work... I mean seriously, there were red flags everywhere.', NULL, 'A yard with a lot of red flags'),
  ('Dad', 'My son just became a father for the first time today... to pass the paternal torch, he asked me where I kept all my dad jokes, so I told him - they are stored in my dadabase.', NULL, 'A very secure safe with a big lock'),
  ('Dad', 'The CEO of Pepsi was fired this morning. He tested positive for coke.', NULL, 'Coke versus Pepsi challenge'),
  ('Dad', 'What happens to a dad joke once it is delivered? It''s fully groan', NULL, 'People growning at a bad joke'),
  ('Dad', 'What starts with ''w'' and ends with ''hat''. (No, that wasn''t a question, just a statement of fact...)', NULL, 'A hat with a W on it'),
  ('Dad', 'When does a bad pun become a dad joke? When it becomes apparent', NULL, 'A first time parent'),
  ('Dad', 'When is a dad joke apparent? When it is delivered', NULL, 'A baby being delivered'),
  ('Dad', 'Why don''t cannibals eat clowns? Because they taste funny.', NULL, 'Clowns being funny'),  ('Engineers', 'Normal: if it ain''t broke, don''t fix it. Engineer: if it ain''t broke, it doesn''t have enough features yet.', NULL, 'A broken toy'),
  ('Did''ya Hear', 'Did you hear about the dyslexic agnostic insomniac who stays up all night wondering if there really is a Dog?', NULL, 'Did you hear about the dyslexic agnostic insomniac who stays up all night wondering if there really is a Dog?'),
  ('Did''ya Hear', 'Did you hear about the underwear company that only allowed brief phone calls?', NULL, 'Did you hear about the underwear company that only allowed brief phone calls?'),
  ('Did''ya Hear', 'Did''ya hear about the cheese factory explosion in Wisconsin? De brie was everywhere', NULL, 'A cheese factory explosion'),
  ('Did''ya Hear', 'Did''ya hear about the guy who broke both his left arm and left leg? He''s all right now.', NULL, 'A person with a broken arm and broken leg'),
  ('Did''ya Hear', 'Did''ya hear about the guy who got hit in the head with a can of soda? He was lucky it was a soft drink.', NULL, 'A can of soda falling on someone''s head'),
  ('Did''ya Hear', 'Did''ya hear about the kidnapping at school? Everything''s fine now. He woke up.', NULL, 'A child taking a nap'),
  ('Did''ya Hear', 'Did''ya hear about the movie ''Constipation''? No? That''s because it hasn''t come out yet', NULL, 'Someone on the toilet'),
  ('Did''ya Hear', 'Did''ya hear about the new broom that came out? It''s sweeping the nation', NULL, 'Someone sweeping the room with a broom'),
  ('Did''ya Hear', 'Did''ya hear about the new restaurant on the moon? The food is ok but there''s no atmosphere', NULL, 'A restaurant on the moon'),
  ('Did''ya Hear', 'Did''ya hear that SpaceX launched several cows into orbit? It was the herd shot around the world.', NULL, 'Cows in space suits'),
  ('Did''ya Hear', 'Did''ya hear the one about the skeleton that couldn''t go to the party? He had no body to go with', NULL, 'A skeleton going to a party'),
  ('Did''ya Hear', 'Did''ya know alligators can grow up to 15 feet? Most only have 4 though.', NULL, 'An alligator with 8 feet'),
  ('Did''ya Hear', 'Did''ya know the latest version of the Oxford English Dictionary does not contain the word ''gullible''?', NULL, 'A large Oxford English Dictionary'),
  ('Engineers', 'Optimist: the glass is half-full. Pessimist: the glass is half-empty. Engineer: that glass is twice as big as it needs to be.', NULL, 'A half-full glass'),
  ('Engineers', 'The graduate with a science degree asks, ''Why does it work?'' The graduate with an engineering degree asks, ''How does it work?'' The graduate with an accounting k asks, ''How much will it cost?'' The graduate with an arts degree asks, ''Do you want fries with that?''', NULL, 'A fast food drive through window'),
  ('Engineers', 'Two engineering students were walking across a university campus when one said, ''Where did you get such a great bike?'' The second engineer replied, ''Well, I was walking along yesterday, minding my own business, when a beautiful woman rode up on this bike, threw it to the ground, took off all her clothes and said, ''Take what you want.'' The first engineer nodded approvingly and said, ''Good choice; the clothes probably wouldn''t have fit you anyway.''', NULL, 'A girl on a bicycle'),
  ('Facts', '10.0 times 0.1 is hardly ever 1.0.', NULL, '10.0 times 0.1 is hardly ever 1.0.'),
  ('Facts', '111,111,111 x 111,111,111 = 12,345,678,987,654,321', NULL, '111,111,111 x 111,111,111 = 12,345,678,987,654,321'),
  ('Facts', '186,000/mps: it''s not just a good idea, it''s the law.', NULL, '186,000/mps: it''s not just a good idea, it''s the law.'),
  ('Facts', '2 + 2 = 5 for extremely large values of 2.', NULL, '2 + 2 = 5 for extremely large values of 2.'),
  ('Facts', 'A camel has 3 eyelids.', 'Snapple bottle cap', 'A camel has 3 eyelids.'),
  ('Facts', 'A chicken is a means for one egg to produce another.', 'George Bernard Shaw (1856-1950)', 'A chicken is a means for one egg to produce another.'),
  ('Facts', 'A crocodile cannot stick out its tongue.', NULL, 'A crocodile cannot stick out its tongue.'),
  ('Facts', 'A flashlight is a case for holding dead batteries.', NULL, 'A flashlight is a case for holding dead batteries.'),
  ('Facts', 'A snail breathes through it''s foot.', 'Snapple bottle cap', 'A snail breathes through it''s foot.'),
  ('Facts', 'A snail can sleep for three years.', NULL, 'A snail can sleep for three years.'),
  ('Facts', 'A sneeze travels at over 100 miles per hour.', 'Snapple bottle cap', 'A sneeze travels at over 100 miles per hour.'),
  ('Facts', 'Actor Tommy Lee Jones and vice-president Al Gore were freshman roommates at Harvard', NULL, 'Actor Tommy Lee Jones and vice-president Al Gore were freshman roommates at Harvard'),
  ('Facts', 'All of the clocks in the movie ''Pulp Fiction'' are stuck on 4:20.', NULL, 'All of the clocks in the movie ''Pulp Fiction'' are stuck on 4:20.'),
  ('Facts', 'All polar bears are left handed.', NULL, 'All polar bears are left handed.'),
  ('Facts', 'Any ship can be a minesweeper ... once.', NULL, 'Any ship can be a minesweeper ... once.'),
  ('Facts', 'Anybody can win, unless there happens to be a second entry.', NULL, 'Anybody can win, unless there happens to be a second entry.'),
  ('Facts', 'Anything free is worth what you paid for it.', NULL, 'Anything free is worth what you paid for it.'),
  ('Facts', 'At some point in your life, you will do an Elvis impersonation.', NULL, 'At some point in your life, you will do an Elvis impersonation.'),
  ('Facts', 'Average life span of a major league baseball: 7 pitches.', NULL, 'Average life span of a major league baseball: 7 pitches.'),
  ('Facts', 'Babies are born without knee caps. They don''t appear until the child reaches 2 to 6 years of age.', NULL, 'Babies are born without knee caps. They don''t appear until the child reaches 2 to 6 years of age.'),
  ('Facts', 'Ballpoint pens never run out of ink; they get lost.', NULL, 'Ballpoint pens never run out of ink; they get lost.'),
  ('Facts', 'Bargain: Something you can''t use at a price you can''t resist.', NULL, 'Bargain: Something you can''t use at a price you can''t resist.'),
  ('Facts', 'Debra Winger was the voice of E.T.', NULL, 'Debra Winger was the voice of E.T.'),
  ('Facts', 'Did you know that eye drops today use the same ingredients as were used in China 5,000 years ago?', NULL, 'Did you know that eye drops today use the same ingredients as were used in China 5,000 years ago?'),
  ('Facts', 'Fact: ''fasten'' and ''loosen'' have opposite meanings. Yet, attach the prefix ''un-'' to both and the words mean the same.', NULL, 'Fact: ''fasten'' and ''loosen'' have opposite meanings. Yet, attach the prefix ''un-'' to both and the words mean the same.'),
  ('Facts', 'Fact: the ten most frequently used words in the English language (making up about one-fourth of all our reading) are: the, of, and, a, to, in, is, I, that, it.', NULL, 'Fact: the ten most frequently used words in the English language (making up about one-fourth of all our reading) are: the, of, and, a, to, in, is, I, that, it.'),
  ('Facts', 'Fact: the vocabulary of the average person consists of five to  six thousand words.', NULL, 'Fact: the vocabulary of the average person consists of five to  six thousand words.'),
  ('Facts', 'Fish cough.', 'Snapple bottle cap', 'Fish cough.'),
  ('Facts', 'If Barbie were life-size, her measurements would be 39-23-33.  She would stand 7 foot tall and have a neck twice the length of a normal human''s neck.', NULL, 'If Barbie were life-size, her measurements would be 39-23-33.  She would stand 7 foot tall and have a neck twice the length of a normal human''s neck.'),
  ('Facts', 'If the No. 2 pencil is the most popular pencil, why is it still No. 2?', 'Snapple bottle cap', 'If the No. 2 pencil is the most popular pencil, why is it still No. 2?'),
  ('Facts', 'If the software is free, YOU are the product', NULL, 'If the software is free, YOU are the product'),
  ('Facts', 'James Doohan, who plays Lt. Commander Montgomery Scott on Star Trek, is missing the entire middle finger of his right hand.', NULL, 'James Doohan, who plays Lt. Commander Montgomery Scott on Star Trek, is missing the entire middle finger of his right hand.'),
  ('Facts', 'Lizards communicate by doing pushups.', 'Snapple bottle cap', 'Lizards communicate by doing pushups.'),
  ('Facts', 'Marilyn Monroe had six toes.', NULL, 'Marilyn Monroe had six toes.'),
  ('Facts', 'Months that begin on a Sunday will always have a ''Friday the 13th.''', NULL, 'Months that begin on a Sunday will always have a ''Friday the 13th.'''),
  ('Facts', 'Mosquitoes are attrracted to people who have recently eaten bananas.', 'Snapple bottle cap', 'Mosquitoes are attrracted to people who have recently eaten bananas.'),
  ('Facts', 'On average, 100 people choke to death on ballpoint pens every year.', NULL, 'On average, 100 people choke to death on ballpoint pens every year.'),
  ('Facts', 'Pearls melt in vinegar.', NULL, 'Pearls melt in vinegar.'),
  ('Facts', 'Slugs have 4 noses', 'Snapple bottle cap', 'Slugs have 4 noses'),
  ('Facts', 'Squids can have eyes the size of a volleyball.', 'Snapple bottle cap', 'Squids can have eyes the size of a volleyball.'),
  ('Facts', 'The catfish has over 27,000 taste buds.', NULL, 'The catfish has over 27,000 taste buds.'),
  ('Facts', 'The name Jeep came from the abbreviation used in the army for the ''General Purpose'' vehicle, G.P.', NULL, 'The name Jeep came from the abbreviation used in the army for the ''General Purpose'' vehicle, G.P.'),
  ('Facts', 'The name Wendy was made up for the book ''Peter Pan''.', NULL, 'The name Wendy was made up for the book ''Peter Pan''.'),
  ('Facts', 'The only 15 letter word that can be spelled without repeating a letter is uncopyrightable.', NULL, 'The only 15 letter word that can be spelled without repeating a letter is uncopyrightable.'),
  ('Facts', 'The Pentagon in Arlington, Virginia, has twice as many bathrooms as necessary. When it was built in the 1940''s, the state of Virginia still had segregation laws requiring separate toilet facilities for blacks and whites.', NULL, 'The Pentagon in Arlington, Virginia, has twice as many bathrooms as necessary. When it was built in the 1940''s, the state of Virginia still had segregation laws requiring separate toilet facilities for blacks and whites.'),
  ('Facts', 'The world''s termites outweigh the world''s humans 10 to 1.', NULL, 'The world''s termites outweigh the world''s humans 10 to 1.'),
  ('Facts', 'There are 293 ways to make change for a dollar.', NULL, 'There are 293 ways to make change for a dollar.'),
  ('Facts', 'There are 3 kinds of people: those who can count and those who can''t.', NULL, 'There are 3 kinds of people: those who can count and those who can''t.'),
  ('Facts', 'There are an average of 178 sesame seeds on a McDonald''s Big Mac bun.', NULL, 'There are an average of 178 sesame seeds on a McDonald''s Big Mac bun.'),
  ('Facts', 'There are only 10 types of people in the world: Those who understand binary, and those who don''t.', NULL, 'There are only 10 types of people in the world: Those who understand binary, and those who don''t.'),
  ('Facts', 'There are three classes of people: the haves, the have-nots, and the still paying for it''s.', NULL, 'There are three classes of people: the haves, the have-nots, and the still paying for it''s.'),
  ('Facts', 'Twinkle, Twinkle, Little Star was composed by Mozazrt when he was 5 years old.', 'Snapple bottle cap', 'Twinkle, Twinkle, Little Star was composed by Mozazrt when he was 5 years old.'),
  ('Good Question!', 'Can fat people go skinny-dipping?', NULL, 'Can fat people go skinny-dipping?'),
  ('Good Question!', 'Can one bird make a pun? No, but toucan', NULL, 'A toucan'),
  ('Good Question!', 'Can you be a closet claustrophobic?', NULL, 'Can you be a closet claustrophobic?'),
  ('Good Question!', 'Can you buy an entire chess set in a pawn-shop?', NULL, 'Can you buy an entire chess set in a pawn-shop?'),
  ('Good Question!', 'Despite the cost of living, have you noticed how it remains so popular?', NULL, 'Despite the cost of living, have you noticed how it remains so popular?'),
  ('Good Question!', 'Did Noah keep his bees in archives?', NULL, 'Did Noah keep his bees in archives?'),
  ('Good Question!', 'Did you know that the next second is really only a second away?  OOPS - you missed it.', NULL, 'Did you know that the next second is really only a second away?  OOPS - you missed it.'),
  ('Good Question!', 'Didn''t you ever wonder how Santa Claus got into your house when you didn''t even have a chimney?', NULL, 'Didn''t you ever wonder how Santa Claus got into your house when you didn''t even have a chimney?'),
  ('Good Question!', 'Did''ya hear about the chameleon that couldn''t change color? He had a reptile dysfunction', NULL, 'A chameleon'),
  ('Good Question!', 'Do cemetery workers prefer the graveyard shift?', NULL, 'Do cemetery workers prefer the graveyard shift?'),
  ('Good Question!', 'Do hungry crows have ravenous appetites?', NULL, 'Do hungry crows have ravenous appetites?'),
  ('Good Question!', 'Do people in Australia call the rest of the world ''up over''?', NULL, 'Do people in Australia call the rest of the world ''up over''?'),
  ('Good Question!', 'Do people who think they know everything really know everything?', NULL, 'Do people who think they know everything really know everything?'),
  ('Good Question!', 'Do pilots take crash-courses?', NULL, 'Do pilots take crash-courses?'),
  ('Good Question!', 'Do radioactive cats have 18 half-lives?', NULL, 'Do radioactive cats have 18 half-lives?'),
  ('Good Question!', 'Do stars clean themselves with meteor showers?', NULL, 'Do stars clean themselves with meteor showers?'),
  ('Good Question!', 'Do you know why computer scientists confuse Christmas and Halloween? Because 31 OCT = 25 DEC.', NULL, 'Do you know why computer scientists confuse Christmas and Halloween? Because 31 OCT = 25 DEC.'),
  ('Good Question!', 'Do you think that when they asked George Washington for ID that he just whipped out a quarter?', NULL, 'Do you think that when they asked George Washington for ID that he just whipped out a quarter?'),
  ('Good Question!', 'Does killing time damage eternity?', NULL, 'Does killing time damage eternity?'),
  ('Good Question!', 'Does the name Pavlov ring a bell?', NULL, 'Does the name Pavlov ring a bell?'),
  ('Good Question!', 'Ever notice that when you move your couch you find many unusual items?', NULL, 'Ever notice that when you move your couch you find many unusual items?'),
  ('Good Question!', 'Ever slip a bar of chocolate into your pocket, ''just for a second''?', NULL, 'Ever slip a bar of chocolate into your pocket, ''just for a second''?'),
  ('Good Question!', 'Ever stop to think, and forget to start again?', NULL, 'Ever stop to think, and forget to start again?'),
  ('Good Question!', 'Ever walk into a room full of mind readers playing charades?', NULL, 'Ever walk into a room full of mind readers playing charades?'),
  ('Good Question!', 'Have you ever imagined a world with no hypothetical situations?', NULL, 'Have you ever imagined a world with no hypothetical situations?'),
  ('Good Question!', 'Have you ever seen a toad on a toadstool?', NULL, 'Have you ever seen a toad on a toadstool?'),
  ('Good Question!', 'How can there be self-help ''groups''?', NULL, 'How can there be self-help ''groups''?'),
  ('Good Question!', 'How come in baseball when you strike out it''s bad, and in bowling it''s good?', NULL, 'How come in baseball when you strike out it''s bad, and in bowling it''s good?'),
  ('Good Question!', 'How do you get off a non-stop flight?', NULL, 'How do you get off a non-stop flight?'),
  ('Good Question!', 'How do you lift an elephant with one hand? You can''t, because elephants don''t have any hands.', NULL, 'An elephant '),
  ('Good Question!', 'How do you tell when you''re out of invisible ink?', NULL, 'How do you tell when you''re out of invisible ink?'),
  ('Good Question!', 'How do you write zero in Roman numerals?', NULL, 'How do you write zero in Roman numerals?'),
  ('Good Question!', 'How does NASA organize a party? They planet', NULL, 'Planets in the solar system'),
  ('Good Question!', 'How is mercury a liquid at room temperature, yet a large solid when orbiting close to the sun?', NULL, 'Mercury orbiting the sun'),
  ('Good Question!', 'How many Germans does it take to screw in a light bulb? Just one. They are very efficient and not very funny.', NULL, 'A screwing in a light bulb, looking angry'),
  ('Good Question!', 'How many of you believe in telekinesis? Raise my hands...', NULL, 'How many of you believe in telekinesis? Raise my hands...'),
  ('Good Question!', 'How many programmers does it take to change a lightbulb? None. It''s a hardware problem.', NULL, 'How many programmers does it take to change a lightbulb? None. It''s a hardware problem.'),
  ('Good Question!', 'How many weeks are there in a light year?', NULL, 'How many weeks are there in a light year?'),
  ('Good Question!', 'If a book about failures doesn''t sell, is it a success?', NULL, 'If a book about failures doesn''t sell, is it a success?'),
  ('Good Question!', 'If a jogger runs at the speed of sound, can he still hear his walkman?', NULL, 'If a jogger runs at the speed of sound, can he still hear his walkman?'),
  ('Good Question!', 'If a parsley farmer is sued, can they garnish his wages?', NULL, 'If a parsley farmer is sued, can they garnish his wages?'),
  ('Good Question!', 'If a pig can''t squeal, does that mean it''s disgruntled?', NULL, 'A squealing pig'),
  ('Good Question!', 'If a stealth bomber crashes in a forest, will it make a sound?', NULL, 'If a stealth bomber crashes in a forest, will it make a sound?'),
  ('Good Question!', 'If a train station is where the train stops, what is a work station?', NULL, 'If a train station is where the train stops, what is a work station?'),
  ('Good Question!', 'If athletes get athlete''s foot, do astronauts get mistletoe?', NULL, 'If athletes get athlete''s foot, do astronauts get mistletoe?'),
  ('Good Question!', 'If Barbie''s so popular, why do you have to buy all her friends?', NULL, 'If Barbie''s so popular, why do you have to buy all her friends?'),
  ('Good Question!', 'If blind people wear dark glasses, why don''t deaf people wear earmuffs?', NULL, 'If blind people wear dark glasses, why don''t deaf people wear earmuffs?'),
  ('Good Question!', 'If Catholics only have mass on Sundays, do they cease to exist the rest of the week?', NULL, 'A Catholics church'),
  ('Good Question!', 'If cats and dogs didn''t have fur would we still pet them?', NULL, 'If cats and dogs didn''t have fur would we still pet them?'),
  ('Good Question!', 'If ice floats, why is Antarctica at the bottom of the earth?', NULL, 'A map of Antarctica'),
  ('Good Question!', 'If peanut butter cookies are made from peanut butter, then what are Girl Scout cookies made out of?', NULL, 'If peanut butter cookies are made from peanut butter, then what are Girl Scout cookies made out of?'),
  ('Good Question!', 'If shoelaces always untie and headphone always tangle, why don''t we use headphone cables in shoes and shoelaces in headphones?', NULL, 'A shoelaces that is untied'),
  ('Good Question!', 'If space is a vacuum, who changes the bags?', NULL, 'If space is a vacuum, who changes the bags?'),
  ('Good Question!', 'If the cops arrest a mime, do they tell him he has the right to remain silent?', NULL, 'If the cops arrest a mime, do they tell him he has the right to remain silent?'),
  ('Good Question!', 'If the funeral procession is at night, do folks drive with their lights off?', NULL, 'If the funeral procession is at night, do folks drive with their lights off?'),
  ('Good Question!', 'If the speed of light is 186,000 miles per second, what''s the speed of heavy?', NULL, 'If the speed of light is 186,000 miles per second, what''s the speed of heavy?'),
  ('Good Question!', 'If tin whistles are made out of tin, what do they make fog horns out of?', NULL, 'If tin whistles are made out of tin, what do they make fog horns out of?'),
  ('Good Question!', 'If white wine goes with fish, do white grapes go with sushi?', NULL, 'If white wine goes with fish, do white grapes go with sushi?'),
  ('Good Question!', 'If you can''t drink and drive, why do bars have parking lots?', NULL, 'If you can''t drink and drive, why do bars have parking lots?'),
  ('Good Question!', 'If you had everything, where would you keep it?', NULL, 'If you had everything, where would you keep it?'),
  ('Good Question!', 'If you jog backwards, will you gain weight?', NULL, 'If you jog backwards, will you gain weight?'),
  ('Good Question!', 'If you try to fail, and succeed, which have you done?', NULL, 'If you try to fail, and succeed, which have you done?'),
  ('Good Question!', 'If you''re cross-eyed and have dyslexia, can you read all right?', NULL, 'If you''re cross-eyed and have dyslexia, can you read all right?'),
  ('Good Question!', 'Is coffee a miracle drug? I think so.', NULL, 'Is coffee a miracle drug? I think so.'),
  ('Good Question!', 'Is it ethical to yell ''Movie!'' in a crowded firehouse?', NULL, 'Is it ethical to yell ''Movie!'' in a crowded firehouse?'),
  ('Good Question!', 'Is it possible to be totally partial?', NULL, 'Is it possible to be totally partial?'),
  ('Good Question!', 'Is sloppiness in speech caused by ignorance or apathy?', NULL, 'Is sloppiness in speech caused by ignorance or apathy?'),
  ('Good Question!', 'Is the glass half empty, half full, or twice as large as it needs to be?', NULL, 'Is the glass half empty, half full, or twice as large as it needs to be?'),
  ('Good Question!', 'Is there an imaginary cure for hypochondria?', NULL, 'Is there an imaginary cure for hypochondria?'),
  ('Good Question!', 'OK, so what''s the speed of dark?', NULL, 'OK, so what''s the speed of dark?'),
  ('Good Question!', 'Weekend, where are you?', NULL, 'Weekend, where are you?'),
  ('Good Question!', 'What animal jumps higher than a house? Any animal. Houses can''t jump.', NULL, 'A kangaroo jumping over a house'),
  ('Good Question!', 'What color is a chameleon sitting on a mirror?', NULL, 'What color is a chameleon sitting on a mirror?'),
  ('Good Question!', 'What days are the strongest? Saturday and Sunday, because the rest are weekdays', NULL, 'A weekly calendar'),
  ('Good Question!', 'What did the bra say to the hat? You go on ahead - I''ll give these two a lift', NULL, 'Someone wearing a bra and a hat'),
  ('Good Question!', 'What did the gingerbread man put on his bed to keep warm at night? A cookie sheet', NULL, 'A gingerbread man on a bed'),
  ('Good Question!', 'What do Eskimos get from sitting on the ice too long? Polaroids.', NULL, 'Eskimos sitting on a chair by their igloo'),
  ('Good Question!', 'What do prisoners use to call each other? Cell phones.', NULL, 'Prisoners in a jail'),
  ('Good Question!', 'What do you get from a pampered cow? Spoiled milk.', NULL, 'A cow in a field wearing a bell'),
  ('Good Question!', 'What do you get when you cross a joke with a rhetorical question?', NULL, 'A confused comedian'),
  ('Good Question!', 'What does a grape say when it''s stepped on? Nothing - it just lets out a little wine', NULL, 'A grape being squished'),
  ('Good Question!', 'What does a turkey in space sound like?   Hubble, hubble, hubble.', NULL, 'What does a turkey in space sound like?   Hubble, hubble, hubble.'),
  ('Good Question!', 'What does the dentist of the year get? A little plaque', NULL, 'A crazy dentist'),
  ('Good Question!', 'What happens if you get scared half to death twice?', NULL, 'What happens if you get scared half to death twice?'),
  ('Good Question!', 'What is a zebra? 26 sizes larger than an ''A'' bra.', NULL, 'A zebra wearing a bra'),
  ('Good Question!', 'What is the search for Noah''s boat called? ''ark''eology', NULL, 'Noah''s ark'),
  ('Good Question!', 'What kind of bagel can fly? A plain bagel', NULL, 'A bagel flying through the air'),
  ('Good Question!', 'What lies at the bottom of the ocean and twitches? A nervous wreck.', NULL, 'A shipwreck on the bottom of the ocean'),
  ('Good Question!', 'What was the best thing *before* sliced bread?', NULL, 'What was the best thing *before* sliced bread?'),
  ('Good Question!', 'What''s another word for thesaurus?', 'Steven Wright', 'What''s another word for thesaurus?'),
  ('Good Question!', 'What''s another word for thesaurus?', NULL, 'What''s another word for thesaurus?'),
  ('Good Question!', 'What''s orange and sounds like a parrot? A carrot', NULL, 'A parrot with a carrot'),
  ('Good Question!', 'What''s the best time of day? 6:30, hands down.', NULL, 'Analog clock showing 6:30 pm'),
  ('Good Question!', 'When is a door not a door? When it''s ajar', NULL, 'An open door'),
  ('Good Question!', 'When it rains, why don''t sheep shrink?', NULL, 'When it rains, why don''t sheep shrink?'),
  ('Good Question!', 'When was the last time you woke up from a nightmare laughing?', NULL, 'When was the last time you woke up from a nightmare laughing?'),
  ('Good Question!', 'Where are average things built? In the satisfactory', NULL, 'A factory '),
  ('Good Question!', 'Where did Noah keep the bees? In the Ark Hives', NULL, 'Noah''s ark'),
  ('Good Question!', 'Where do sharks go on vacation? Finland', NULL, 'Sharks in the ocean'),
  ('Good Question!', 'Why are electrical outlets always so far away from the plug?', NULL, 'Why are electrical outlets always so far away from the plug?'),
  ('Good Question!', 'Why can''t life''s big problems come when we are twenty and know everything ?', NULL, 'Why can''t life''s big problems come when we are twenty and know everything ?'),
  ('Good Question!', 'Why can''t you hear a pterodactyl going to the bathroom? Because the ''P'' is silent', NULL, 'A pterodactyl'),
  ('Good Question!', 'Why do cows wear bells? Because their horns don''t work!', NULL, 'A cow with very large horns'),
  ('Good Question!', 'Why do flamingoes lift one leg up? If they lifted both they''d fall', NULL, 'Pink flamingoes'),
  ('Good Question!', 'Why do gorillas have big nostrils? Because they have big fingers.', NULL, 'A gorilla with a finger in it''s nose'),
  ('Good Question!', 'Why do men''s and women''s shirts button opposite ways?', NULL, 'Why do men''s and women''s shirts button opposite ways?'),
  ('Good Question!', 'Why do people let the phone ring twice before answering when they are sitting right next to it?', NULL, 'Why do people let the phone ring twice before answering when they are sitting right next to it?'),
  ('Good Question!', 'Why do psychics have to ask you for your name?', NULL, 'Why do psychics have to ask you for your name?'),
  ('Good Question!', 'Why do so many foods come packaged in plastic? It''s quite uncanny.', NULL, 'Why do so many foods come packaged in plastic? It''s quite uncanny.'),
  ('Good Question!', 'Why do the criminally insane get to have all the fun?', NULL, 'Why do the criminally insane get to have all the fun?'),
  ('Good Question!', 'Why do the signs that say ''Slow Children'' have a picture of a running child?', NULL, 'Why do the signs that say ''Slow Children'' have a picture of a running child?'),
  ('Good Question!', 'Why do they call it ''chili'' if it''s hot?', NULL, 'Why do they call it ''chili'' if it''s hot?'),
  ('Good Question!', 'Why do we look so good in a mirror, and yet so lousy in a photograph?', NULL, 'Why do we look so good in a mirror, and yet so lousy in a photograph?'),
  ('Good Question!', 'Why do we sing ''Take me out to the ball game ''when we are already there?', NULL, 'Why do we sing ''Take me out to the ball game ''when we are already there?'),
  ('Good Question!', 'Why do you continue to press Return; it does NOT make me work any faster.', NULL, 'Why do you continue to press Return; it does NOT make me work any faster.'),
  ('Good Question!', 'Why do you never see elephants hiding in trees? Because they''re really good at it!', NULL, 'An elephant in a tree'),
  ('Good Question!', 'Why doesn''t glue stick to the inside of the bottle?', NULL, 'Why doesn''t glue stick to the inside of the bottle?'),
  ('Good Question!', 'Why doesn''t Tarzan have a beard?', NULL, 'Why doesn''t Tarzan have a beard?'),
  ('Good Question!', 'Why experiment on animals with so many lawyers out there?', NULL, 'Why experiment on animals with so many lawyers out there?'),
  ('Good Question!', 'Why is dark spelled with a K and not with a C? Because you can''t C in the dark', NULL, 'The Dark Knight'),
  ('Good Question!', 'Why is it called lipstick if you can still move your lips?', NULL, 'Why is it called lipstick if you can still move your lips?'),
  ('Good Question!', 'Why is it that night falls but day breaks?', NULL, 'Why is it that night falls but day breaks?'),
  ('Good Question!', 'Why is it that when you''re driving and looking for an address, you turn down the volume on the radio?', NULL, 'Why is it that when you''re driving and looking for an address, you turn down the volume on the radio?'),
  ('Good Question!', 'Why is lemon juice made with artificial flavor, and dishwashing liquid made with real lemons?', NULL, 'Why is lemon juice made with artificial flavor, and dishwashing liquid made with real lemons?'),
  ('Good Question!', 'Why is the third hand on the watch called a second hand?', NULL, 'Why is the third hand on the watch called a second hand?'),
  ('Good Question!', 'Why is the time of day with the slowest traffic called rush hour?', NULL, 'Why is the time of day with the slowest traffic called rush hour?'),
  ('Good Question!', 'Why is the word abbreviation so long?', NULL, 'Why is the word abbreviation so long?'),
  ('Good Question!', 'Why wait for spring? Procastinate now!', NULL, 'Why wait for spring? Procastinate now!'),
  ('Good Question!', 'Why was the toilet paper rolling down the mountain? To get to the bottom.', NULL, 'Toilet paper rolling down a mountain'),
  ('Good Question!', 'You know what seems odd to me? Numbers that aren''t divisible by two', NULL, 'Odd numbers'),
  ('Good Question!', 'If people evolved from monkeys, why are monkeys still around?', NULL, 'Monkeys climbing a tree with a person watching them'),
  ('Good Question!', 'Which letter is silent in the word Scent - the S or the C?', NULL, 'A skunk past a giant letter S and a giant letter C'),
  ('Good Question!', 'Why is the letter W called double U? Shouldn''t it be called double V?', NULL, 'A giant letter W'),
  ('Halloween', 'How do you fix a broken pumpkin? With a pumpkin patch', NULL, 'A smashed pumpkin'),
  ('Halloween', 'What is a mummy''s favorite kind of music? Wrap music', NULL, 'A mummy singing a song'),
  ('Halloween', 'What is a skeleton''s favorite snack? Spare ribs', NULL, 'A skeleton missing some ribs'),
  ('Halloween', 'What is the ghost''s favorite desert? I scream', NULL, 'A ghost eating ice cream'),
  ('Halloween', 'Why didn''t the skeleton go to the Halloween party? He had no body to go with', NULL, 'A skeleton at a Halloween party'),
  ('Halloween', 'Why do ghosts go to bars? For the booos', NULL, 'A ghost going into a bar'),
  ('Halloween', 'Why don''t skeletons go trick or treating? They have no body to go with', NULL, 'A skeleton at a Halloween party'),
  ('Hipsters', 'Hipsters love ''Raiders of the Lost Ark'' cuz it was the first Indie film.', NULL, 'A hipster watching a movie'),
  ('Hipsters', 'How did the hipster burn his tongue? He drank his coffee before it was cool', NULL, 'A hipster drinking coffee'),
  ('Hipsters', 'How do you drown a hipster? In the mainstream', NULL, 'Someone drowning in a stream'),
  ('Hipsters', 'How many hipsters does it take to change a light bulb? the number is really obscure and you probably haven''t heard of it', NULL, 'A hipster changing a light bulb'),
  ('Jobs', 'I had a job in an orange juice factory, but I got canned because I couldn''t concentrate.', NULL, 'A can of orange juice concentrate'),
  ('Jobs', 'I once had a job crushing pop cans - it was soda pressing.', NULL, 'Machine to crushing aluminum cans'),
  ('Jobs', 'I spent one summer as a kid working on a rabbit farm - that was a hare raising experience!', NULL, 'A rabbit farm'),
  ('Jobs', 'I used to be a banker, but then I lost interest.', NULL, 'A banker making a loan'),
  ('Jobs', 'I used to work at a calendar factory, but I got fired cuz I took a couple of days off', NULL, 'A calendar missing some days'),
  ('Jobs', 'I used to work at a keyboard factory, but I got fired because I didn''t put in enough shifts', NULL, 'A keyboard factory'),
  ('Jobs', 'I want a job cleaning mirrors. It''s a job I can see myself doing.', NULL, 'A person cleaning a mirror'),
  ('Jobs', 'I wasn''t happy being a glue salesman, but I stuck with it.', NULL, 'Someone selling a bottle of glue'),
  ('Jobs', 'If you ever need an ark, I Noah guy.', NULL, 'Noah''s ark'),
  ('Jobs', 'Nobody could believe I worked on road construction, but when they came over to my house - all the signs were there.', NULL, 'Road construction signs'),
  ('Jobs', 'That guy who invented LifeSavers? They say he made a mint', NULL, 'A roll of LifeSavers candy'),
  ('Jobs', 'The man who fell into the upholstery machine is fully recovered.', NULL, 'Reupholstery equipment'),
  ('Knock Knock', 'KK/WT: Boo? Don''t cry, it''s only a joke', NULL, 'A ghost crying'),
  ('Knock Knock', 'KK/WT: Broken Pencil ? Never mind - it''s pointless', NULL, 'A broken pencil'),
  ('Knock Knock', 'KK/WT: Cows go ? No silly - owls go Hoo, cows go Moo', NULL, 'An owl sitting on a cow'),
  ('Knock Knock', 'KK/WT: Echo ? Bless you', NULL, 'Someone sneezing'),
  ('Knock Knock', 'KK/WT: Impatient Cow ? (interrupt them) Moo!', NULL, 'A cow saying Moo!'),
  ('Knock Knock', 'KK/WT: Scold ? It''s cold outside - let me in!', NULL, 'A child out in the cold'),
  ('Knock Knock', 'KK/WT: Spell ? (spell who?) : W H O', NULL, 'Spell the word who'),
  ('Knock Knock', 'Whoever invented the knock knock joke should get a no bell prize', NULL, 'A door with a doorbell'),
  ('Knock Knock', 'Why are there no knock-knock jokes about ''Merica? \nCuz Freedom Rings', NULL, 'An American flag'),
  ('Knock Knock', 'Why did the chicken cross the road? To get to the idiot''s house.\nKnock Knock. Who''s there?\nChicken!', NULL, 'A dumb chicken crossing the road'),
  ('Knock Knock', 'Will you remember me in a year? (Yes.) \n Will you remember me in a month? (Yes.)\nWill you remember me in a week? (Yes.)\nKnock Knock. Who''s there?\nYou forgot me already?!', NULL, 'Someone trying to remember something'),
  ('Pirates', 'Did you know that Pirates were the first people to insulate their homes? They did it for the ''RRRR'' value.', NULL, 'A Pirate putting insulation in the walls of his house'),
  ('Pirates', 'Did''ya hear about the pirate''s parrot that fell in love with a duck? The bird kept saying, ''Polly wants a quacker''.', NULL, 'A parrot sitting beside a duck'),
  ('Pirates', 'How much did the pirate pay for his piercings? A buck-an-ear!', NULL, 'An earring made out of corn'),
  ('Pirates', 'One pirate says to the other, ''Arrrgh, that be a fine looking hook and peg leg ye got for ye''self!'' The pirate replies, ''I would think so, it cost me and arm and a leg!''', NULL, 'A pirate with a hook and a peg leg'),
  ('Pirates', 'What does a Dyslexic Pirate Say? RRAAAAAAAAAAA!', NULL, 'A backwards pirate'),
  ('Pirates', 'What does a pirate drive on vacation? An AAAARRRRRRRRR V.', NULL, 'A pirate driving an RV'),
  ('Pirates', 'What has 8 arms and 8 legs? 8 Pirates!', NULL, '8 Pirates'),
  ('Pirates', 'What is a pirate''s favorite letter of the alphabet?? Ahhh.. yee''d think it''d be R, but me first love B the C!!!', NULL, 'A pirate on his ship at sea'),
  ('Pirates', 'What''s the pirate''s wife''s name? Peggy!', NULL, 'A female pirate with a peg leg'),
  ('Pirates', 'Where can you find a pirate who has lost his wooden legs? Right where you left him.', NULL, 'A pirate who has lost his wooden leg'),
  ('Pirates', 'Where did the one-legged pirate go for breakfast? IHOP!', NULL, 'A pirate eating pancakes'),
  ('Pirates', 'Why are pirates so great? They just RRRRRrrrr!', NULL, 'An awesome pirate'),
  ('Pirates', 'Why did the pirate cross the sea? To get to the other tide!', NULL, 'A pirate on his ship at sea'),
  ('Pirates', 'Why did the pirate join the debate team? Because he liked to Arrrrrrgue!', NULL, 'A pirate arguing with another pirate'),
  ('Pirates', 'Why do pirates like communists? Because they''re from the U.S.S.AARRRRRRRRR!', NULL, 'A pirate with a communist flag'),
  ('Programmers', '!false (it''s funny because it''s true!)', NULL, 'Someone who thinks something is not funny'),
  ('Programmers', '[''hip'',''hip''] (hip hip array!)', NULL, 'A computer programmer'),
  ('Programmers', 'A manager, a programmer, and a data analyst went hunting. The manager shoots at the deer and misses 5 feet to the left. The programmer shoots and misses 5 feet to the right. The data analyst yells out ''We got ''em!''', NULL, 'Three people hunting'),
  ('Programmers', 'A SQL query goes into a bar, walks up to two tables and asks, ''Can I join you?''', NULL, 'Two people sitting at two tables in a bar'),
  ('Programmers', 'Arguing with a woman is like a software license agreement. To get to the end, you ignore everything and say ''I agree''', NULL, 'A man arguing with a woman'),
  ('Programmers', 'How did pirates collaborate before computers ? Pier to pier networking.', NULL, 'A pirate ship moored at a pier'),
  ('Programmers', 'How many engineers does it take to change a lightbulb? Hang on, I''m still flashing the firmware on this one.', NULL, 'An engineer changing a lightbulb'),
  ('Programmers', 'How many programmers does it take to change a light bulb? A: none, that''s a hardware problem', NULL, 'An engineer refusing to change a lightbulb'),
  ('Programmers', 'If you put a million monkeys at a million keyboards, one of them will eventually write a Java program. The rest of them will write Perl programs.', NULL, 'A lot of monkeys typing on keyboards'),
  ('Programmers', 'I''ve got a great UDP joke but I''m afraid you wouldn''t get it', NULL, 'Mail that is undeliverable'),
  ('Programmers', 'Java truly is an OOP language As in: OOPs - I used Java!', NULL, 'A programmer that has made a big mistake'),
  ('Programmers', 'One bad programmer can easily create two jobs a year.', NULL, 'A programmer that has made a big mistake'),
  ('Programmers', 'Programming is like sex: One mistake and you have to support it for the rest of your life.', NULL, 'A programmer that has made a big mistake'),
  ('Programmers', 'Several fonts walk into a bar. ''Get out of here!'' shouts the bartender. ''We don''t serve your type here.''', NULL, 'A bartender in a bar shoting'),
  ('Programmers', 'There''s a new band called 1023MB. They haven''t had any gigs yet.', NULL, 'A musical band composed of computer programmers'),
  ('Programmers', 'To understand what recursion is, you must first understand recursion.', NULL, 'An infinite loop'),
  ('Programmers', 'Unfortunately these jokes only work if you git them.', NULL, 'A computer programmer telling a joke'),
  ('Programmers', 'Unix is user friendly. It''s just very particular about who its friends are.', NULL, 'A sad person with only one friend'),
  ('Programmers', 'What are clouds made of? Mostly linux servers.', NULL, 'Computers sitting in a cloud'),
  ('Programmers', 'What do you call 8 hobbits? A hobbyte', NULL, '8 hobbits'),
  ('Programmers', 'What''s Forrest Gump''s password? 1forest1', NULL, 'Forrest Gump thinking of a password'),
  ('Programmers', 'When your hammer is C, everything begins to look like a thumb.', NULL, 'Someone hitting their thumb with a hammer'),
  ('Programmers', 'Why did the developer go broke? Because he used up all his cache', NULL, 'A computer programmer that has run out of money'),
  ('Programmers', 'Why do Java developers wear glasses? Because they can''t C#', NULL, 'A computer programmer wearing very large glasses'),
  ('Programmers', 'Why doesn''t Objective C have a garbage collector? Because there would be nothing left!', NULL, 'A garbage collector driving down the street'),
  ('Science', 'A physicist is trying to talk a man off the tip of the Empire State Building; he says, ''Don''t jump, you have so much potential!''', NULL, 'A person on the top of the Empire State Building'),
  ('Science', 'Doctor: I''m afraid your DNA is backwards Me: ''AND...?''', NULL, 'A picture of DNA '),
  ('Science', 'I make bad science puns periodically', NULL, 'A periodic table'),
  ('Science', 'I was going to tell a joke about sodium, but then I thought ''Na - nobody will get it''', NULL, 'A box of salt'),
  ('Science', 'Really? I told my best chemistry joke and there was no reaction?', NULL, 'A chemistry bunson burner and a beaker'),
  ('Science', 'Wanna hear a potassium joke? K', NULL, 'The letter K'),
  ('Science', 'Water is heavier than butane fluid because butane is a lighter fluid.', NULL, 'Two bottles on a balancing scale'),
  ('Science', 'Why are there no cats on Mars? Curiosity killed them all', NULL, 'The Mars Curiosity rover'),
  ('Science', 'Why can''t you trust an atom? They make up everything.', NULL, 'An atom making a joke'),
  ('Science', 'You''re living, you occupy space, you have mass. You know what that means? You matter.', NULL, 'A person standing on a scale'),
  ('What do you call...', 'What do you call a bear with no teeth? A gummy bear.', NULL, 'A bear with no teeth'),
  ('What do you call...', 'What do you call a beehive with no exits? Unbelievable!', NULL, 'A beehive on a farm'),
  ('What do you call...', 'What do you call a busy waiter? A server. \nWhat do you call an idle server? A waiter.', NULL, 'A busy waiter in a restaurant'),
  ('What do you call...', 'What do you call a camel with no humps? Humphrey', NULL, 'A camel'),
  ('What do you call...', 'What do you call a cow during an earthquake? A milkshake', NULL, 'A cow in a field'),
  ('What do you call...', 'What do you call a cow with a twitch? Beef Jerky', NULL, 'A cow in a field'),
  ('What do you call...', 'What do you call a cow with no legs? Ground beef', NULL, 'A cow with three legs in a field'),
  ('What do you call...', 'What do you call a dog with no legs? It doesn''t matter - it''s not going to come.', NULL, 'A dog with three legs'),
  ('What do you call...', 'What do you call a duck with a drug problem? A quackhead', NULL, 'A duck walking by a lake'),
  ('What do you call...', 'What do you call a mother cow after it gives birth? De-calf-in-ated', NULL, 'A mother cow and her calf'),
  ('What do you call...', 'What do you call a nose with no body? Nobody knows', NULL, 'A giant nose with no body'),
  ('What do you call...', 'What do you call a sleepwalking nun? A roamin'' Catholic', NULL, 'A sleepwalking nun'),
  ('What do you call...', 'What do you call a three legged hippo? A hoppo', NULL, 'A three legged hippo'),
  ('What do you call...', 'What do you call a very old snowman? Water', NULL, 'A melted snowman'),
  ('What do you call...', 'What do you call an alligator in a vest? An investigator', NULL, 'An alligator wearing a vest'),
  ('What do you call...', 'What do you call an alligator that uses GPS? A navigator', NULL, 'An alligator using a GPS'),
  ('What do you call...', 'What do you call an elephant that doesn''t matter? An irrelephant', NULL, 'An elephant'),
  ('What do you call...', 'What do you call an imaginary color? A pigment of your imagination', NULL, 'A pigment of colors on a pallette'),
  ('What do you call...', 'What do you call cheese that isn''t yours? Nacho Cheese.', NULL, 'A bowl of Nacho Cheese'),
  ('What do you call...', 'What do you call dinosaur with a large vocabulary? A Thesaurus', NULL, 'A very large dinosaur')

------------------------------------------------------------------------------------------------------------------------
IF @RemovePreviousJokes = 'Y'
BEGIN
    Print 'Removing previous set of jokes...'
    Delete From JokeRating
    Delete From JokeCategory
    Delete From Joke
    DBCC CHECKIDENT('JokeRating', RESEED, 1)
    DBCC CHECKIDENT('JokeCategory', RESEED, 1)
    DBCC CHECKIDENT('Joke', RESEED, 1)
END

Print 'Inserting fresh categories...'
INSERT INTO JokeCategory (JokeCategoryTxt)
Select JokeCategoryTxt From @tmpCategory Where JokeCategoryTxt NOT IN (Select JokeCategoryTxt From JokeCategory)

Print 'Inserting fresh jokes...'
Insert into Joke (JokeCategoryId, JokeCategoryTxt, JokeTxt, Attribution, ImageTxt, Rating, VoteCount)
    Select c.JokeCategoryId, c.JokeCategoryTxt, j.JokeTxt, j.Attribution, j.ImageTxt, 0, 0
    From @tmpJokes j INNER JOIN JokeCategory c on j.JokeCategoryTxt = c.JokeCategoryTxt
    Where j.JokeTxt NOT IN (Select JokeTxt From Joke)

Print 'Displaying All Jokes...'
Select j.JokeId, j.JokeCategoryId, j.JokeCategoryTxt, j.JokeTxt, j.ImageTxt, j.Rating, j.CreateDateTime From Joke j ORDER BY j.JokeCategoryTxt, j.JokeTxt
--Select j.JokeId, c.JokeCategoryTxt, j.JokeTxt, j.ImageTxt From Joke j INNER JOIN JokeCategory c on j.JokeCategoryId = c.JokeCategoryId ORDER BY c.JokeCategoryTxt, j.JokeTxt
